### ISSUE TITLE
Manhattan Plot not correct

### ISSUE THREAD

**Issue by MikeKazz** [CERC-Genomic-Medicine/Regenie_nextflow#6]
Hi
It seems like there is a systematic error in Bioinfokit's Manhattan plots where each chromosome is inverse (end to start rather than start to end). Consider using another toolkit.
Compare the two plots below, where one is made with Python and one with Bioinfokit.

![manhatten (2)](https://user-images.githubusercontent.com/85311370/235002540-8adf63b5-9f3e-43cf-9f26-7b37867d1b71.png)

![manhattan_plot (3)](https://user-images.githubusercontent.com/85311370/235002552-504a2c40-4f3a-47a7-9d32-29c3bbd437d8.png)

**Comment by VChapdelaineT** [comment]
Corrected
